// <auto-generated />
namespace Obligatorisk_opg_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BiblioteksMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BiblioteksMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202203081104000_BiblioteksMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
